export const ticketData = [
  {
    img: "/images/plane.jpg",
    title: "Airpeace",
    date: "25th October, 2025",
    time: "10:30 AM",
    from: "Lagos",
    to: "Enugu",
    seat: "Window",
    class: "Economy",
    marketPrice: "45,000",
    discountPrice: "35,000",
    rating: "4.6",
    transactions: "20",
    name: "Emma",
    category: "Flight",
    location: "Abuja",
  },
  {
    img: "/images/airtime.jpg",
    title: "MTN",
    date: "10th July, 2025",
    network: "MTN",
    marketPrice: "5,000",
    discountPrice: "4,000",
    rating: "3.5",
    name: "Sam",
    transactions: "40",
    category: "Airtime",
    location: "Lagos",
  },
  {
    img: "/images/movie.jpg",
    title: "Wankanda",
    date: "14th July, 2025",
    marketPrice: "4,000",
    discountPrice: "2,500",
    rating: "3",
    name: "Mike",
    transactions: "10",
    category: "Movie",
    location: "Abuja",
  },
  {
    img: "/images/train.jpg",
    title: "NRC",
    date: "20th October, 2025",
    time: "8:00 AM",
    from: "Abuja",
    to: "Kaduna",
    seat: "Window",
    class: "Economy",
    marketPrice: "10,000",
    discountPrice: "8,000",
    rating: "4.6",
    transactions: "20",
    name: "Emma",
    category: "Train",
    location: "Abuja",
  },
  {
    img: "/images/concert.jpg",
    title: "Davido Tour",
    date: "10th July, 2025",
    description: "Davido live",
    marketPrice: "5,000",
    discountPrice: "4,000",
    rating: "3.5",
    name: "Abel",
    transactions: "40",
    category: "Concert",
    location: "Abuja",
  },
  {
    img: "/images/movie.jpg",
    title: "Wankanda",
    date: "14th July, 2025",
    marketPrice: "4,000",
    discountPrice: "2,500",
    rating: "3",
    name: "Mike",
    transactions: "10",
    category: "Movie",
    location: "Abuja",
  },
];
